- name: update
  hosts: "{{ var }}"
  vars:
    swap_file_size_mb: '2048'
    install_all_package_updates: true
    install_packages:
    - epel-release
    - mc
    - vim
    - htop
    - rsync
    - gzip
    - unzip
    - java
    - wget
  roles:
    - ansible-packages
    - geerlingguy.swap
    - geerlingguy.git
    - do-agent
  tasks:
    - name: set timezone to UA_Kiev
      timezone:
        name: Europe/Kiev
    - name: Update /etc/hosts
      blockinfile:
        path: /etc/hosts
        create: yes
        block: |
          #HAProxy Staging
          10.2.2.2  haproxy-stag01
          10.2.2.3  haproxy-stag02
          #HAProxy Skvot
          10.1.1.1  haproxy01
          10.1.1.2  haproxy02
          #Skvot PHP7.4

